services:
  - type: web
    name: akram-sweet-shareholders
    plan: starter
    env: python
    region: frankfurt  # region should be same as your database region.
    buildCommand: "./build.sh"
    startCommand: "gunicorn run:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DB_ENGINE
        value: postgresql+psycopg2
      - key: DATABASE_URL
        fromDatabase:
          name: akram-shareholders-db
          property: connectionString
databases:
  - name: akram-shareholders-db
    databaseName: akram_shareholders
    user: akram_user
    plan: free
