services:
  - type: web
    name: akram-sweet-shareholders
    plan: starter
    env: python
    region: frankfurt
    buildCommand: "./build.sh"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: 4
      - key: DB_ENGINE
        value: postgresql+psycopg2
      - key: LOGIN_OTP_ENABLED
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: akram-shareholders-db
          property: connectionString
databases:
  - name: akram-shareholders-db
    databaseName: akram_shareholders
    user: akram_user
    plan: free
